# Site settings
title: Esdras Caleb
description: Full Stack Developer for hire
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://esdrascaleb.github.io/

# User settings
username: Esdras Caleb
user_description: I'm a Full Stack Developer from Brazil, Currently I work with Moodle development at the Federal University of Rio Grande do Norte.
user_title: Full Stack Developer
email: esdrascaleb@gmail.com
twitter_username: EsdrasCaleb
instagram_username: acheicaleb
facebook_username: esdrascaleb
linkedin_username: esdras-caleb
github_username:  EsdrasCaleb
buycoffe_url: esdrascaleb
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

