# Site settings
title: Esdras Caleb
description: FULL Stack Developer
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://esdrascaleb.github.io/

# User settings
username: Esdras Caleb
user_description: I'm a Full Stack Developer and Game Programmer from Brazil
user_title: Full Stack Developer
email: esdrascaleb@gmail.com
twitter_username: EsdrasCaleb
instagram_username: acheicaleb
facebook_username: esdrascaleb
linkedin_username: esdras-caleb
github_username:  EsdrasCaleb
buycoffe_url: esdrascaleb
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
include: [".well-known"]
exclude: ['package.json', 'src', 'node_modules', 'vendor']

